### ISSUE TITLE
Question/Implementation: Internationalization/Locale

### ISSUE THREAD

**Issue by cnvo** [ever-co/feature-requests#11]
**How is this currently implemented?**

Internationalization? Currencies? Languages?

For example MI/KM conversion per country, Miles to Kilometers.

**Comment by evereq** [comment]
@cnvo we have basic support for languages/internationalization, but not currencies yet (WIP like many other things).

For languages, every project has some resource files which you can edit to add translations for a specific locale. We already translated everything into 4 languages: English, Russian, Hebrew, and Bulgarian (because that's what our teams speaking). 

I will add here a link to the relevant part of the documentation when it's ready (every part of the Platform, i.e. every app will have slightly different way to add translations)
